[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
url = "2.5.7"
oauth2 = "5.0.0"
axum = "0.8.6"
tokio = "1.48.0"
thiserror = "2.0.17"
async-trait = "0.1.89"
serde = { version = "1.0.228", features = ["derive"] }

[lib]
doctest = false
